services:
  postgres:
    image: postgres
    container_name: employee_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - employee-network

  chroma:
    image: chromadb/chroma:latest
    container_name: employee_vector_db_container
    restart: unless-stopped
    environment:
      IS_PERSISTENT: "true"
      PERSIST_DIRECTORY: /chroma/chroma
      ANONYMIZED_TELEMETRY: "false"
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - "5433:8000"
    networks:
      - employee-network

  backend:
    build: .
    container_name: employee_backend_container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/employee_db
      - ENVIRONMENT=dev
    networks:
      - employee-network
    develop:
      watch:
        - path: .
          target: /app
          action: sync
        - path: uv.lock
          action: rebuild

volumes:
  postgres_data:
  chromadb_data:

networks:
   employee-network:
     driver: bridge
