"""employee password field

Revision ID: 0ea0da70346c
Revises: 3726b8b6e540
Create Date: 2026-05-29 16:00:41.660448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea0da70346c'
down_revision: Union[str, Sequence[str], None] = '3726b8b6e540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password_hash', sa.Text(), nullable=True))
    op.execute("update employee set password_hash = 'placeholder' where password_hash is null")
    op.alter_column('employee', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'password_hash')
    # ### end Alembic commands ###
