"""init

Revision ID: 19ea6140884c
Revises: 
Create Date: 2026-05-28 16:58:16.870827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ea6140884c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employee', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('employee', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.drop_column('employee', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_column('employee', 'deleted_at')
    op.drop_column('employee', 'updated_at')
    op.drop_column('employee', 'created_at')
    op.drop_column('employee', 'date_of_birth')
    # ### end Alembic commands ###
