"""add employee roles

Revision ID: 1cccda8c1326
Revises: 0ea0da70346c
Create Date: 2026-06-01 14:45:25.866641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cccda8c1326'
down_revision: Union[str, Sequence[str], None] = '0ea0da70346c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

employee_roles = sa.Enum('ADMIN', 'HR', 'ENGINEERING', 'C_SUITE', 'UNASSIGNED', name='employeeroles')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    employee_roles.create(op.get_bind(), checkfirst=True)
    op.add_column('employee', sa.Column('role', employee_roles, server_default='UNASSIGNED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'role')
    employee_roles.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
