"""unique department name

Revision ID: 3726b8b6e540
Revises: dbbec7284f14
Create Date: 2026-05-29 14:15:27.262922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3726b8b6e540'
down_revision: Union[str, Sequence[str], None] = 'dbbec7284f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'department', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='unique')
    # ### end Alembic commands ###
