"""add experience, joining_date and status

Revision ID: e4b2d510b83e
Revises: 1cccda8c1326
Create Date: 2026-06-10 14:57:08.591635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4b2d510b83e"
down_revision: Union[str, Sequence[str], None] = "1cccda8c1326"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum("ACTIVE", "PROBATION", "INACTVE", name="employeestatus")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("employee", sa.Column("joining_date", sa.Date(), nullable=True))
    op.add_column("employee", sa.Column("experience", sa.Text(), nullable=True))
    op.add_column(
        "employee",
        sa.Column("status", status_enum, server_default="ACTIVE", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "status")
    op.drop_column("employee", "experience")
    op.drop_column("employee", "joining_date")
    status_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
